spring.application.name=hdc

spring.profiles.active=${ACTIVE_PROFILE:prod}

spring.flyway.enabled=true

spring.config.import=optional:file:.env[.properties]

api.security.token.secret=${JWS_SECRET:my-secret-super-secret}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projetohoradecuidar@gmail.com
spring.mail.password=pbgw anic jidm atzq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true