spring.application.name=hdc
spring.profiles.active=${ACTIVE_PROFILE:dev}
spring.flyway.enabled=true

spring.config.import=optional:file:.env[.properties]

api.security.token.secret=${JWS_SECRET:my-secret-super-secret}
