spring.application.name=hdc

spring.profiles.active=${ACTIVE_PROFILE:prod}

spring.flyway.enabled=true

spring.config.import=optional:file:.env[.properties]

frontend.url=${FRONTEND_URL:'http://localhost:5173'}

api.security.token.secret=${JWS_SECRET}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudflare.r2.account-id=${R2_ACCOUNT_ID}
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.bucket=hdc-images
cloudflare.r2.region=auto

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

admin.address=${ADMIN_ADDRESS:admin@gmail.com}
