ALTER TABLE usuarios
    ALTER COLUMN data_de_nascimento DROP NOT NULL,
    ALTER COLUMN telefone DROP NOT NULL,
    ALTER COLUMN rua DROP NOT NULL,
    ALTER COLUMN bairro DROP NOT NULL,
    ALTER COLUMN estado DROP NOT NULL,
    ALTER COLUMN cidade DROP NOT NULL;
